services:
  db:
    image: postgres:18-alpine
    container_name: revenue_postgres_db
    restart: always
    environment:
      POSTGRES_USER: reveneue
      POSTGRES_PASSWORD: reveneue123
      POSTGRES_DB: revenue_data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
